# przepływ pracy pokazujący, jak tworzyć przepływy pracy w gałęziach
name: Develop in a Branch
on: [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: |
            echo "Przepływ pracy wyzwolony w odgałęzieniu '${{ github.ref }}'"    
            echo "Przepływ pracy wyzwolony przez zdarzenie '${{ github.event_name }}'"        
            echo "Przepływ pracy wyzwolony przez aktora '${{ github.actor }}'"
            echo "Tytuł pull requesta to '${{ github.event.pull_request.title }}'"
      - run: |
            echo "::debug::To jest komunikat debugowania"
            echo "::notice::To jest komunikat powiadomienia"
            echo "::warning::To jest komunikat ostrzegawczy"
            echo "::error::To jest komunikat o błędzie"
      - uses: actions/checkout@v4.2.2
      - uses: devops-actions/actionlint@v0.1.9